# Identificação do Projeto
sonar.organization=diogomarassi
sonar.projectKey=DiogoMarassi_backend

# Onde o código está e o que deve ser ignorado
sonar.sources=.
sonar.exclusions=node_modules/**, .next/**, out/**, build/**

