name: CI/CD Pipeline - Backend Node.js

on:
  push:
    branches:
      - master # ou master, dependendo do padrão do seu repositório

jobs:
  # 1. Análise de Qualidade com SonarQube
  sonarcloud:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        # Pinado na versão v4.2.2
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=DiogoMarassi_backend
            -Dsonar.organization=diogomarassi
            -Dsonar.sources=.
            -Dsonar.exclusions=node_modules/**
  # 2. Deploy na AWS EC2 (Só roda se o Sonar passar)
  deploy:
    name: Deploy to EC2
    needs: sonarcloud
    runs-on: ubuntu-latest
    steps:
      - name: Executar comandos na EC2 via SSH
        # Pinado na versão v1.0.3 em vez de @master
        uses: appleboy/ssh-action@08304c40590059f3d5386001d8100e47087e5b60 
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Entra na pasta do seu projeto (Lembre-se de ajustar o nome abaixo!)
            cd /var/www/back/NOME_DA_SUA_PASTA
            
            # 2. Puxa as novidades do GitHub
            git pull origin main
            
            # 3. Instala pacotes novos e sincroniza o banco
            npm install
            npx prisma generate
            npx prisma db push
            
            # 4. Refaz o build do NestJS com o código novo
            npm run build
            
            # 5. Reinicia a API no PM2
            pm2 restart backend-api
